---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    name: spark-master
spec:
  ports:
  - port: 7077
    name: spark-master
    targetPort: 7077
    protocol: TCP
    nodePort: 7077
  selector:
    app: spark
  type: NodePort


