---
kind: Service
apiVersion: v1
metadata:
  name: spark-master
  labels:
    app: spark-master
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: jupyter-http
    - port: 8080
      targetPort: 8080
      name: spark-http
    - port: 8998
      targetPort: 8998
      name: livy-http
    - port: 7077
      name: spark-master
      targetPort: 7077
  selector:
    component: spark-master
  type: ClusterIP
