apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: etlconsumer
  name: etlconsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etlconsumer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: etlconsumer
    spec:
      containers:
        - env:
            - name: INDEX_HOST
              value: elasticsearch
            - name: MARIADB_HOST
              value: mariadb
            - name: MARIADB_PASSWORD
              value: gaddar
            - name: kafka_brokers
              value: kafka-np:30092
            - name: kafka_interval
              value: "8000"
          image: rnctech/etlconsumer:latest
          name: etlconsumer
          resources: {}
      restartPolicy: Always
status: {}
